server:
  port: 8001
  servlet:
    context-path: /

spring:
  zipkin:
    service:
      name: budget-service
    base-url: http://localhost:9411
    sender:
      type: web
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
